### ISSUE TITLE
nu merg comenzile.

### ISSUE THREAD

**Issue by sinibeleaua** [m0untain04/Controlul-de-Calitate-BOT#1]
l-am adaugat pe server si dau comenzile si nu se intampla nimic

**Comment by m0untain04** [comment]
Mie imi merg comenzile perfect. Poate nu ai creat permisiuni la bot pt. a citi mesajele.
Ma poti contacta pe discord daca tot nu ii dai de cap: m0untain#7471
![image](https://user-images.githubusercontent.com/65610893/208429890-a11c405c-f231-4640-9e9f-5897eeafb1fe.png)
